version: "3.8"
volumes: 
  postgres-data:
services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pedroamstalden@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "saladadefrutas"
    ports:
      - "54321:80"
    depends_on:
      - postgres
